SET (CMAKE_SYSTEM_NAME Linux)
SET (CMAKE_SYSTEM_PROCESSOR i686)

SET (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -m32" CACHE STRING "C Flags")
SET (CMAKE_ASM_FLAGS "${CMAKE_C_FLAGS} -m32" CACHE STRING "ASM Flags")
